title: Rachel Woodruff
description: Professional Portfolio
theme: jekyll-theme-modernist
# or try: jekyll-theme-cayman, jekyll-theme-slate, etc.

# Optional settings
email: rachelwoodruff08@gmail.com

# Build settings
markdown: kramdown
